# Generated by Django 4.2.2 on 2023-06-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "author",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthorBook",
            fields=[
                ("author_book_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "author_book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "book",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "book_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "book_category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "favorite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("loan_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "loan",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "member",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "reservation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "review",
                "managed": False,
            },
        ),
    ]
